### ISSUE TITLE
주문은 어떻게 하는건가요?

### ISSUE THREAD

**Issue by d10000usd** [devKangMinHyeok/React-Upbit-API-Example#1]
안녕하세용 ~ 질문드립니다. 
업비트 주문은 어떻게 하나요?
nodejs 로 하는 방식이 있는데, 

node
// const rp = require("./request-promise")
// const sign = require("jsonwebtoken").sign
// const queryEncode = require("querystring").encode
모듈 받아서 그대로 쓰면 되는거라 간단한데. 

vue, react 로는 하는 방식을 모르겠어서 문의글 드립니다. 
react 대응 모듈을 모르겠어서 질문드립니다. 

계좌 조회까지만 되는 드라이버가 있으면 다른 주문 알고리즘은 하면 되는데. 
secretKey, token 을 어떻게 넘기는지 잘모르겠습니다. 

알려 주실수 있을 까요?

**Comment by devKangMinHyeok** [comment]
안녕하십니까
use-upbit-api npm 패키지는 주문 API는 기능이 지원되지 않고, 저도 시세 조회만 경험이 있어 답변이 어려울 것 같습니다.
인터넷 서칭으로 해결이 안되신다면, 업비트 API에 직접 문의 메일 써보시는 것을 추천드립니다.
예전에 문의 메일을 써본 경험이 있는데, 잘 답변해주셨습니다.
